name: Publish website

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    name: Build & deploy website
    runs-on: ubuntu-latest
    if: github.repository == 'Orange-OpenSource/La-Va11ydette'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.6.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          keep_files: true
          cname: la-va11ydette.orange.com
